from collections.abc import Sequence
from typing import final

@final
class InferenceConfig:
    def __new__(cls, /, confidence_threshold: float = 0.25, iou_threshold: float = 0.45, max_det: int = 300, half: bool = False, save: bool = True, save_frames: bool = False, rect: bool = True, imgsz: tuple[int, int] |None = None, num_threads: int = 0, batch: int |None = None) -> InferenceConfig: ...

@final
class Model:
    def __new__(cls, /, value: str) -> Model: ...
    def load(self, /) -> Prediction: ...
    def with_config(self, /, config: InferenceConfig) -> Model: ...

@final
class Prediction:
    def predict(self, /, path: str) -> list[Results]: ...
    def predict_batch(self, /, paths: Sequence[str]) -> list[list[Results]]: ...
    def predict_bytes(self, /, data: bytes, path: str) -> list[Results]: ...
    def predict_dir(self, /, dir: str) -> list[tuple[SourceMeta, Results]]: ...
    def predict_glob(self, /, pattern: str) -> list[tuple[SourceMeta, Results]]: ...
    def predict_stream(self, /, url: str) -> list[tuple[SourceMeta, Results]]: ...
    def predict_url(self, /, url: str) -> list[tuple[SourceMeta, Results]]: ...
    def predict_video(self, /, path: str) -> list[tuple[SourceMeta, Results]]: ...
    def predict_webcam(self, /, index: int) -> list[tuple[SourceMeta, Results]]: ...

@final
class Results:
    def __repr__(self, /) -> str: ...
    @property
    def boxes(self, /) -> list[list[float]] |None: ...
    @property
    def keypoints(self, /) -> list[list[float]] |None: ...
    @property
    def masks(self, /) -> list[list[float]] |None: ...
    @property
    def names(self, /) -> dict[int, str]: ...
    @property
    def obb(self, /) -> list[list[float]] |None: ...
    @property
    def orig_shape(self, /) -> tuple[int, int]: ...
    @property
    def path(self, /) -> str: ...
    @property
    def probs(self, /) -> list[float] |None: ...
    @property
    def speed(self, /) -> tuple[float, float, float]: ...

@final
class SourceMeta:
    @property
    def fps(self, /) -> float |None: ...
    @property
    def frame_idx(self, /) -> int: ...
    @property
    def path(self, /) -> str: ...
    @property
    def total_frames(self, /) -> int |None: ...
